### ISSUE TITLE
can line number record?

### ISSUE THREAD

**Issue by byadair** [google/textfsm#109]
Hi, I am processing a huge log, in a few times I need to track the line number of unexpected data which got from textfsm. 
I found the line_num only used in Exceptions in code.
can I get line number using textfsm? thanks

**Comment by harro** [comment]
line_num is only used for errors in parsing the template.

If the template is valid but not matching the text expected in the input data then it is unclear to me what line number to return. Given a record can be built from data extracted from different lines of the input file, including filldown data from previous matches, then there is no 1:1 relationship between records and lines in the data source.

We could add line number to the 'Error' operation. At present it returns the line number of the matching rule and the actual input data line that matched but not the line number of the line of data. The downside here is that in order to use this operator it would be necessary to 'Error'-out and cease parsing when you may actually want to proceed further i.e. it is non recoverable ... and the line number would only be useful where the line of data is insufficient for locating where in the input data is located in the source data.

Are you aware of the 'Error' operator and does this address your use case (as is), or is a line number as part of the Error output required?

**Comment by byadair** [comment]
Thank you for your reply, I do not think the Error action will solve my problem, I just want to know which line have the record, and jump to that line for further analysis after got all the data in table.
Since this issue is a bit long, I think I have to close this issue, the project I was working for is closed.
Still thank you for your reply
